name: python package ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.7.16", "3.8.20"]
        django: ["3.2.25"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          pip install -e .
          pip install django==${{ matrix.django }}
      - name: Run tests
        run: python runtests.py
