name: python package ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        versions: [
          {python: '3.7', django: '1.11.29'},
          {python: '3.7', django: '2.2.28'},
        ]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.versions.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.versions.python }}
      - name: Install Dependencies
        run: |
          pip install -e .
          pip install django==${{ matrix.versions.django }}
      - name: Run tests
        run: python runtests.py
